/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project1;


import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import static project1.Project1.URL;

import static project1.Project1.PASSWORD;
import static project1.Project1.USER;



/**
 *
 * @author flash 20-9-2018
 */
public class AdminForm extends javax.swing.JFrame {

    /**
     * Creates new form AdminForm
     */
    
     String permission = ""  , user = "";
          String id= "";
          ADMIN admin = new ADMIN();
    public AdminForm() {
      
        initComponents();
        String [] permission = {"Allowed" , "Not Allowed"};
        JComboBox c = new JComboBox(permission);
        jTable2.getColumnModel().getColumn(4).setCellEditor(new DefaultCellEditor(c));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        createbugptn = new javax.swing.JButton();
        viewprojectsptn = new javax.swing.JButton();
        updatetesterptn = new javax.swing.JButton();
        adduserptn = new javax.swing.JButton();
        createprojectptn = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        cardpanels = new javax.swing.JPanel();
        AddEmployee_panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        EmployeeName = new javax.swing.JTextField();
        EmployyeEmail = new javax.swing.JTextField();
        EmployeePassword = new javax.swing.JTextField();
        EmployeeJob = new javax.swing.JComboBox<>();
        AddEmployee = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        IDTEXT = new javax.swing.JTextField();
        UpdatePermissionPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        UpdateButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        NameTEXT = new javax.swing.JTextField();
        EmailTEXT = new javax.swing.JTextField();
        JobTEXT = new javax.swing.JTextField();
        PermissionTEXT = new javax.swing.JTextField();
        createprojectpanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Project_nameTEXT = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        AssignedProjects = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        Add = new javax.swing.JButton();
        AssigntoTEXT = new javax.swing.JTextField();
        createbugpanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        bug_Name = new javax.swing.JTextField();
        add_bug = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        Bug_id = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        viewprojectpanel = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        viewprojectsandbug = new javax.swing.JTable();
        viewbugpanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(170, 483));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setBorder(new javax.swing.border.MatteBorder(null));

        createbugptn.setBackground(new java.awt.Color(0, 0, 51));
        createbugptn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        createbugptn.setForeground(new java.awt.Color(51, 51, 255));
        createbugptn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/Create_48px.png"))); // NOI18N
        createbugptn.setText("Create Bugs");
        createbugptn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        createbugptn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        createbugptn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        createbugptn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createbugptnActionPerformed(evt);
            }
        });

        viewprojectsptn.setBackground(new java.awt.Color(0, 0, 51));
        viewprojectsptn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewprojectsptn.setForeground(new java.awt.Color(51, 51, 255));
        viewprojectsptn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/View_48px.png"))); // NOI18N
        viewprojectsptn.setText("View Projects");
        viewprojectsptn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        viewprojectsptn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        viewprojectsptn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        viewprojectsptn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewprojectsptnActionPerformed(evt);
            }
        });

        updatetesterptn.setBackground(new java.awt.Color(0, 0, 51));
        updatetesterptn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updatetesterptn.setForeground(new java.awt.Color(51, 51, 255));
        updatetesterptn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/Registry Editor_48px.png"))); // NOI18N
        updatetesterptn.setText("Update Permission");
        updatetesterptn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        updatetesterptn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        updatetesterptn.setMaximumSize(new java.awt.Dimension(95, 25));
        updatetesterptn.setMinimumSize(new java.awt.Dimension(95, 25));
        updatetesterptn.setPreferredSize(new java.awt.Dimension(95, 25));
        updatetesterptn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatetesterptnActionPerformed(evt);
            }
        });

        adduserptn.setBackground(new java.awt.Color(0, 0, 51));
        adduserptn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        adduserptn.setForeground(new java.awt.Color(51, 51, 255));
        adduserptn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/Add User Male_48px.png"))); // NOI18N
        adduserptn.setText("Add User");
        adduserptn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        adduserptn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        adduserptn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        adduserptn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adduserptnActionPerformed(evt);
            }
        });

        createprojectptn.setBackground(new java.awt.Color(0, 0, 51));
        createprojectptn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        createprojectptn.setForeground(new java.awt.Color(51, 51, 255));
        createprojectptn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/Create_48px.png"))); // NOI18N
        createprojectptn.setText("Create Project");
        createprojectptn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        createprojectptn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        createprojectptn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        createprojectptn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createprojectptnActionPerformed(evt);
            }
        });

        Back.setBackground(new java.awt.Color(0, 0, 51));
        Back.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Back.setForeground(new java.awt.Color(51, 255, 255));
        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/back.png"))); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/Bug_50px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createbugptn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(viewprojectsptn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(updatetesterptn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(adduserptn, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
            .addComponent(createprojectptn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(Back))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(adduserptn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updatetesterptn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(createprojectptn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(createbugptn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewprojectsptn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Back)
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        cardpanels.setBackground(new java.awt.Color(255, 255, 255));
        cardpanels.setLayout(new java.awt.CardLayout());

        AddEmployee_panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Employee Name :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Employee Job :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Employee Email :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Employee Password :");

        EmployeeJob.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tester", "Developer", " " }));

        AddEmployee.setBackground(new java.awt.Color(255, 255, 255));
        AddEmployee.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AddEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/Add_64px.png"))); // NOI18N
        AddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmployeeActionPerformed(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("ID : ");

        javax.swing.GroupLayout AddEmployee_panelLayout = new javax.swing.GroupLayout(AddEmployee_panel);
        AddEmployee_panel.setLayout(AddEmployee_panelLayout);
        AddEmployee_panelLayout.setHorizontalGroup(
            AddEmployee_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddEmployee_panelLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(AddEmployee_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(AddEmployee_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddEmployee_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(EmployyeEmail)
                        .addComponent(EmployeePassword)
                        .addComponent(EmployeeJob, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(IDTEXT, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(376, Short.MAX_VALUE))
            .addGroup(AddEmployee_panelLayout.createSequentialGroup()
                .addGap(392, 392, 392)
                .addComponent(AddEmployee)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AddEmployee_panelLayout.setVerticalGroup(
            AddEmployee_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddEmployee_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddEmployee_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDTEXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(AddEmployee_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(AddEmployee_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmployeeJob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(AddEmployee_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmployyeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(AddEmployee_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmployeePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AddEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AddEmployee.getAccessibleContext().setAccessibleDescription("add new Employee ");

        cardpanels.add(AddEmployee_panel, "card8");

        UpdatePermissionPanel.setBackground(new java.awt.Color(255, 255, 255));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Email", "Job", "Permission"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        UpdateButton.setBackground(new java.awt.Color(255, 255, 255));
        UpdateButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        UpdateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/Registry Editor_48px.png"))); // NOI18N
        UpdateButton.setText("Update ^_^");
        UpdateButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Name :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Email :");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Job :");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Permission :");

        javax.swing.GroupLayout UpdatePermissionPanelLayout = new javax.swing.GroupLayout(UpdatePermissionPanel);
        UpdatePermissionPanel.setLayout(UpdatePermissionPanelLayout);
        UpdatePermissionPanelLayout.setHorizontalGroup(
            UpdatePermissionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdatePermissionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UpdatePermissionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel11))
                .addGap(33, 33, 33)
                .addGroup(UpdatePermissionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdatePermissionPanelLayout.createSequentialGroup()
                        .addGroup(UpdatePermissionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameTEXT)
                            .addComponent(JobTEXT)
                            .addGroup(UpdatePermissionPanelLayout.createSequentialGroup()
                                .addComponent(PermissionTEXT, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(EmailTEXT))
                        .addGap(132, 132, 132))
                    .addGroup(UpdatePermissionPanelLayout.createSequentialGroup()
                        .addComponent(UpdateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        UpdatePermissionPanelLayout.setVerticalGroup(
            UpdatePermissionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdatePermissionPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(UpdatePermissionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(NameTEXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(UpdatePermissionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(EmailTEXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(UpdatePermissionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(JobTEXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(UpdatePermissionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(PermissionTEXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(UpdatePermissionPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        cardpanels.add(UpdatePermissionPanel, "card7");

        createprojectpanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Project Name : ");

        AssignedProjects.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Email", "Project"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        AssignedProjects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AssignedProjectsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(AssignedProjects);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Assign to ->");

        Add.setBackground(new java.awt.Color(255, 255, 255));
        Add.setFont(new java.awt.Font("Tempus Sans ITC", 2, 24)); // NOI18N
        Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/Add_64px.png"))); // NOI18N
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        AssigntoTEXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssigntoTEXTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createprojectpanelLayout = new javax.swing.GroupLayout(createprojectpanel);
        createprojectpanel.setLayout(createprojectpanelLayout);
        createprojectpanelLayout.setHorizontalGroup(
            createprojectpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createprojectpanelLayout.createSequentialGroup()
                .addGroup(createprojectpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createprojectpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(createprojectpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGroup(createprojectpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(createprojectpanelLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(AssigntoTEXT, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(createprojectpanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(Project_nameTEXT, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(createprojectpanelLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        createprojectpanelLayout.setVerticalGroup(
            createprojectpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createprojectpanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(createprojectpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Project_nameTEXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(createprojectpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AssigntoTEXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
        );

        cardpanels.add(createprojectpanel, "card5");

        createbugpanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Bug Name :");

        add_bug.setBackground(new java.awt.Color(255, 255, 255));
        add_bug.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        add_bug.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/Add_64px.png"))); // NOI18N
        add_bug.setBorder(null);
        add_bug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_bugActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("bug ID :");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Tester :");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText(" Project :");

        javax.swing.GroupLayout createbugpanelLayout = new javax.swing.GroupLayout(createbugpanel);
        createbugpanel.setLayout(createbugpanelLayout);
        createbugpanelLayout.setHorizontalGroup(
            createbugpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createbugpanelLayout.createSequentialGroup()
                .addGroup(createbugpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createbugpanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(createbugpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19)
                            .addComponent(jLabel10))
                        .addGap(71, 71, 71)
                        .addGroup(createbugpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Bug_id, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(createbugpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING, 0, 130, Short.MAX_VALUE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(add_bug, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(createbugpanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(bug_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(540, Short.MAX_VALUE))
        );
        createbugpanelLayout.setVerticalGroup(
            createbugpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createbugpanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(createbugpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(bug_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(createbugpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Bug_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(34, 34, 34)
                .addGroup(createbugpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(33, 33, 33)
                .addGroup(createbugpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(add_bug)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        cardpanels.add(createbugpanel, "card4");

        viewprojectpanel.setBackground(new java.awt.Color(0, 51, 204));

        viewprojectsandbug.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "bug id", "bug name", "project"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(viewprojectsandbug);

        javax.swing.GroupLayout viewprojectpanelLayout = new javax.swing.GroupLayout(viewprojectpanel);
        viewprojectpanel.setLayout(viewprojectpanelLayout);
        viewprojectpanelLayout.setHorizontalGroup(
            viewprojectpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
        );
        viewprojectpanelLayout.setVerticalGroup(
            viewprojectpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
        );

        cardpanels.add(viewprojectpanel, "card3");

        viewbugpanel.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "BUG"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout viewbugpanelLayout = new javax.swing.GroupLayout(viewbugpanel);
        viewbugpanel.setLayout(viewbugpanelLayout);
        viewbugpanelLayout.setHorizontalGroup(
            viewbugpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewbugpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 952, Short.MAX_VALUE))
        );
        viewbugpanelLayout.setVerticalGroup(
            viewbugpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewbugpanelLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );

        cardpanels.add(viewbugpanel, "card2");

        jPanel7.setBackground(new java.awt.Color(51, 0, 51));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/Administrator Male_48px.png"))); // NOI18N
        jLabel3.setText("Admin^_^");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(19, 19, 19))
        );

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("We Are The Five Team ^_^");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardpanels, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(19, 19, 19)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardpanels, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1134, 531));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adduserptnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adduserptnActionPerformed
        // TODO add your handling code here:
        cardpanels.removeAll();
        cardpanels.add(AddEmployee_panel);
        cardpanels.repaint();
        cardpanels.revalidate();
    }//GEN-LAST:event_adduserptnActionPerformed

    private void updatetesterptnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatetesterptnActionPerformed
      {
        Connection Conn = null ;
      //  String Q = "SELECT name_emp, email_emp FROM employee";
        try {
            
           Conn = (Connection) DriverManager.getConnection(URL, USER,PASSWORD);
            Statement ST = Conn.createStatement();
            ResultSet RS = ST.executeQuery("SELECT id,username, email, job, permission FROM user");
            while(jTable2.getRowCount() > 0)
            {
               ((DefaultTableModel)jTable2.getModel()).removeRow(0);
            }
            int col = RS.getMetaData().getColumnCount();
            while(RS.next())
            {
                Object [] rows = new Object[col];
                for(int i = 1 ; i<=col ; i++)
                {
                    rows[i-1] = RS.getObject(i);
                }
                ((DefaultTableModel)jTable2.getModel()).insertRow(RS.getRow() - 1, rows);
            }
            System.out.println("YESSS");
            RS.close();
            ST.close();
          
            
        } catch (Exception e) {
            System.out.println("NO");
        }
    }
        
        cardpanels.removeAll();
        cardpanels.add(UpdatePermissionPanel);
        cardpanels.repaint();
        cardpanels.revalidate();
    }//GEN-LAST:event_updatetesterptnActionPerformed

    private void createprojectptnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createprojectptnActionPerformed
        
         loadData();
        cardpanels.removeAll();
        cardpanels.add(createprojectpanel);
        cardpanels.repaint();
        cardpanels.revalidate();
    }//GEN-LAST:event_createprojectptnActionPerformed

    private void createbugptnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createbugptnActionPerformed
       
        loading_testers(); loading_projects();
        cardpanels.removeAll();
        cardpanels.add(createbugpanel);
        cardpanels.repaint();
        cardpanels.revalidate();
    }//GEN-LAST:event_createbugptnActionPerformed

    private void viewprojectsptnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewprojectsptnActionPerformed
        // TODO add your handling code here:
       // loadprojectandbug();
        if(!admin.ViewBugwUpdate(viewprojectsandbug))
        {
            JOptionPane.showMessageDialog(this, "Check Connection to DataBase", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        cardpanels.removeAll();
        cardpanels.add(viewprojectpanel);
        cardpanels.repaint();
        cardpanels.revalidate();
    }//GEN-LAST:event_viewprojectsptnActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
      menu show = new menu();
      show.setVisible(true);
      this.hide();
        
       
    }//GEN-LAST:event_BackActionPerformed
// Done here ;
    private void AddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmployeeActionPerformed
      String name = EmployeeName.getText();
      String password = EmployeePassword.getText();
      String Email = EmployyeEmail.getText();
      String Job = EmployeeJob.getSelectedItem().toString();
      String id = IDTEXT.getText();
      if(admin.CreateUser(name, password, Email, Job , id))
          JOptionPane.showMessageDialog(this, "Successfully Added" , "Done" , JOptionPane.PLAIN_MESSAGE);
      else 
          JOptionPane.showMessageDialog(this, "Error while adding a new user , check the developer for information", "ERROR", JOptionPane.ERROR_MESSAGE);
      EmployeeName.setText("");
       EmployeePassword.setText("");
         EmployyeEmail.setText("");
         IDTEXT.setText("");
      
    }//GEN-LAST:event_AddEmployeeActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
if(admin.UpdatePermission(permission, id)) 
{
    JOptionPane.showMessageDialog(this, "Successfully Updated", "Done", JOptionPane.PLAIN_MESSAGE);
    System.out.println(id+ " " + permission);
    PermissionTEXT.setText(permission);
}
else 
{
     JOptionPane.showMessageDialog(this, "Update Failed", "ERROR", JOptionPane.ERROR_MESSAGE);
}
NameTEXT.setText("");EmailTEXT.setText("");JobTEXT.setText("");PermissionTEXT.setText("");
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
            
            int row = jTable2.getSelectedRow();
            permission = jTable2.getModel().getValueAt(row, 4).toString(); 
            id = jTable2.getModel().getValueAt(row, 0).toString();
            String ID = jTable2.getModel().getValueAt(row, 0).toString();
            String Name = jTable2.getModel().getValueAt(row, 1).toString();
            String Email =  jTable2.getModel().getValueAt(row, 2).toString();
            String Job =  jTable2.getModel().getValueAt(row, 3).toString();
            String Permission =  jTable2.getModel().getValueAt(row, 4).toString();
            EmailTEXT.setText(Email);
            NameTEXT.setText(Name);
            JobTEXT.setText(Job);
            PermissionTEXT.setText(Permission);
// TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    private void AssignedProjectsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AssignedProjectsMouseClicked
     int column = 0;
     int row = AssignedProjects.getSelectedRow();
     id = AssignedProjects.getModel().getValueAt(row, column).toString();
     String name = AssignedProjects.getModel().getValueAt(row, 1).toString();
     AssigntoTEXT.setText(name);
    }//GEN-LAST:event_AssignedProjectsMouseClicked

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        String ProjectName = Project_nameTEXT.getText();
        //System.out.println(id);
        if(admin.CreateProject(id, ProjectName))
        {
            JOptionPane.showMessageDialog(this, "Successfully Updated", "Done", JOptionPane.PLAIN_MESSAGE);
        }
        else 
        {
            JOptionPane.showMessageDialog(this, "Update Failed", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
      
        
        
    }//GEN-LAST:event_AddActionPerformed

    private void add_bugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_bugActionPerformed
       
        String bug_name = ""  , bug_id = "" , project = "" ;
        project = jComboBox2.getSelectedItem().toString();
        bug_name = bug_Name.getText(); bug_id = Bug_id.getText();
        System.out.println(bug_name +" "+ bug_id +" "+ project +" " + jComboBox1.getSelectedItem().toString());
       if( admin.CreateBug(bug_name, bug_id , project , jComboBox1.getSelectedItem().toString()))
       {
           JOptionPane.showMessageDialog(this, "Successfully updated", "Done", JOptionPane.PLAIN_MESSAGE);
       }
       else 
       {
            JOptionPane.showMessageDialog(this, "Update Failed", "ERROR", JOptionPane.ERROR_MESSAGE);
       }
       /* try {
            String Query = "INSERT INTO `database`.bug (id, name ,status, project) \n" +
"	VALUES ('"+bug_id+"','"+bug_name+"' ,'not done', '"+project+"');";
            Connection Con = DriverManager.getConnection(URL, USER, PASSWORD);
            Statement st = Con.createStatement();
            st.executeUpdate(Query);
            System.out.println(bug_id + " " + bug_name +" " + project);
        } catch (Exception e) {
            System.out.println("it's not done");
        }*/
    }//GEN-LAST:event_add_bugActionPerformed

    private void AssigntoTEXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssigntoTEXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AssigntoTEXTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton AddEmployee;
    private javax.swing.JPanel AddEmployee_panel;
    private javax.swing.JTable AssignedProjects;
    private javax.swing.JTextField AssigntoTEXT;
    private javax.swing.JButton Back;
    private javax.swing.JTextField Bug_id;
    private javax.swing.JTextField EmailTEXT;
    private javax.swing.JComboBox<String> EmployeeJob;
    private javax.swing.JTextField EmployeeName;
    private javax.swing.JTextField EmployeePassword;
    private javax.swing.JTextField EmployyeEmail;
    private javax.swing.JTextField IDTEXT;
    private javax.swing.JTextField JobTEXT;
    private javax.swing.JTextField NameTEXT;
    private javax.swing.JTextField PermissionTEXT;
    private javax.swing.JTextField Project_nameTEXT;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JPanel UpdatePermissionPanel;
    private javax.swing.JButton add_bug;
    private javax.swing.JButton adduserptn;
    private javax.swing.JTextField bug_Name;
    private javax.swing.JPanel cardpanels;
    private javax.swing.JPanel createbugpanel;
    private javax.swing.JButton createbugptn;
    private javax.swing.JPanel createprojectpanel;
    private javax.swing.JButton createprojectptn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton updatetesterptn;
    private javax.swing.JPanel viewbugpanel;
    private javax.swing.JPanel viewprojectpanel;
    private javax.swing.JTable viewprojectsandbug;
    private javax.swing.JButton viewprojectsptn;
    // End of variables declaration//GEN-END:variables

    void loadData()
    {
        Connection Conn = null ;
     
        try {
            
           Conn = (Connection) DriverManager.getConnection(URL, USER,PASSWORD);
            Statement ST = Conn.createStatement();
            ResultSet RS = ST.executeQuery("SELECT id,username,email, project  FROM `user`");
            while(AssignedProjects.getRowCount() > 0)
            {
               ((DefaultTableModel)AssignedProjects.getModel()).removeRow(0);
            }
            int col = RS.getMetaData().getColumnCount();
            while(RS.next())
            {
                Object [] rows = new Object[col];
                for(int i = 1 ; i<=col ; i++)
                {
                    rows[i-1] = RS.getObject(i);
                }
                ((DefaultTableModel)AssignedProjects.getModel()).insertRow(RS.getRow() - 1, rows);
            }
            System.out.println("loaded");
            RS.close();
            ST.close();
        } catch (Exception e) {
            System.out.println("NOt loaded");
        }
     
    }
    void loading_testers()
    {
           try {
        String Query = "SELECT username  from user\n" +
            "where job = 'tester' and project is null" ;
        Connection Conn = DriverManager.getConnection(URL, USER, PASSWORD);
        Statement St = Conn.createStatement();
        ResultSet Rs = St.executeQuery(Query);
        while(Rs.next())
        {
            jComboBox1.addItem(Rs.getString(1));
        }
        System.out.println("filled");
    } catch (SQLException e) {
        System.out.println("not filled , try again");
    }
    }
    void loading_projects()
    {
          try {
        String Query = "SELECT project  from user WHERE project is not null";
        Connection Conn = DriverManager.getConnection(URL, USER, PASSWORD);
        Statement St = Conn.createStatement();
        ResultSet Rs = St.executeQuery(Query);
        while(Rs.next())
        {
            jComboBox2.addItem(Rs.getString(1));
        }
        System.out.println("filled");
    } catch (SQLException e) {
        System.out.println("not filled , try again");
    }
    }
    void loadprojectandbug()
    {
         Connection Conn = null ;
     
        try {
            
           Conn = (Connection) DriverManager.getConnection(URL, USER,PASSWORD);
            Statement ST = Conn.createStatement();
            ResultSet RS = ST.executeQuery("SELECT * from bug");
            while(viewprojectsandbug.getRowCount() > 0)
            {
               ((DefaultTableModel)viewprojectsandbug.getModel()).removeRow(0);
            }
            int col = RS.getMetaData().getColumnCount();
            while(RS.next())
            {
                Object [] rows = new Object[col];
                for(int i = 1 ; i<=col ; i++)
                {
                    rows[i-1] = RS.getObject(i);
                }
                ((DefaultTableModel)viewprojectsandbug.getModel()).insertRow(RS.getRow() - 1, rows);
            }
            System.out.println("loaded projects");
            RS.close();
            ST.close();
        } catch (Exception e) {
            System.out.println("NOt loaded projects");
        }
    }
   
}
