// Developer Form 
package project1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static project1.Project1.PASSWORD;
import static project1.Project1.URL;
import static project1.Project1.USER;



public final class DeveloperForm extends javax.swing.JFrame {

    String Bug_ID = "" , status = "" ;
   String DevloperName;
   String DeveloperPassword ;
   String DeveloperEmail = "";
   String DeveloperId = "";
   String DeveloperProject = "";
   String Email = "" ;String id = "";
   Developer ND = null;
    public DeveloperForm(Developer Dev) {
        initComponents();
        String [] status = {"Done" , "Not Done"};
        JComboBox c = new JComboBox(status);
        UpdateBug.getColumnModel().getColumn(3).setCellEditor(new DefaultCellEditor(c));
         ND = Dev;
         
         DevloperName = Dev.getUsername();
         DeveloperPassword = Dev.getPassword();
         DeveloperEmail = Dev.getEmail();
         DeveloperId = Dev.getId();
         DeveloperProject= Dev.getProject();
       
        
          loadprojectandbug();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        viewbugsptn = new javax.swing.JButton();
        updatebugsptn = new javax.swing.JButton();
        resetmydataptn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cardpanels = new javax.swing.JPanel();
        viewbugspanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Bugs = new javax.swing.JTable();
        viewprojectpanel = new javax.swing.JPanel();
        updatebugspanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        UpdateBug = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BugIDTEXT = new javax.swing.JTextField();
        BugNameTEXT = new javax.swing.JTextField();
        projectTEXT = new javax.swing.JTextField();
        statusTEXT = new javax.swing.JTextField();
        updatebug = new javax.swing.JButton();
        resetmydatapanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        UserName = new javax.swing.JTextField();
        Password = new javax.swing.JTextField();
        EamilReset = new javax.swing.JTextField();
        updateData = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setMinimumSize(new java.awt.Dimension(120, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 395));

        viewbugsptn.setBackground(new java.awt.Color(51, 51, 51));
        viewbugsptn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        viewbugsptn.setForeground(new java.awt.Color(204, 255, 255));
        viewbugsptn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/View Details_48px.png"))); // NOI18N
        viewbugsptn.setText("View Bugs\\projects");
        viewbugsptn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        viewbugsptn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        viewbugsptn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbugsptnActionPerformed(evt);
            }
        });

        updatebugsptn.setBackground(new java.awt.Color(51, 51, 51));
        updatebugsptn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updatebugsptn.setForeground(new java.awt.Color(204, 255, 255));
        updatebugsptn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/Registry Editor_50px.png"))); // NOI18N
        updatebugsptn.setText("Update Bugs");
        updatebugsptn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        updatebugsptn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        updatebugsptn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebugsptnActionPerformed(evt);
            }
        });

        resetmydataptn.setBackground(new java.awt.Color(51, 51, 51));
        resetmydataptn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        resetmydataptn.setForeground(new java.awt.Color(204, 255, 255));
        resetmydataptn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/33333.png"))); // NOI18N
        resetmydataptn.setText("Reset My Data");
        resetmydataptn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        resetmydataptn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        resetmydataptn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetmydataptnActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/Bug_50px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewbugsptn, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(updatebugsptn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(resetmydataptn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(74, 74, 74))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addGap(21, 21, 21)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(viewbugsptn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(updatebugsptn)
                .addGap(27, 27, 27)
                .addComponent(resetmydataptn)
                .addGap(183, 183, 183))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setText("We Are The Five Team ^_^");

        cardpanels.setBackground(new java.awt.Color(255, 255, 255));
        cardpanels.setLayout(new java.awt.CardLayout());

        viewbugspanel.setBackground(new java.awt.Color(255, 255, 255));

        Bugs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bug ID", "Bug Name", "Project"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Bugs);

        javax.swing.GroupLayout viewbugspanelLayout = new javax.swing.GroupLayout(viewbugspanel);
        viewbugspanel.setLayout(viewbugspanelLayout);
        viewbugspanelLayout.setHorizontalGroup(
            viewbugspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewbugspanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 985, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        viewbugspanelLayout.setVerticalGroup(
            viewbugspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewbugspanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        cardpanels.add(viewbugspanel, "card5");

        viewprojectpanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout viewprojectpanelLayout = new javax.swing.GroupLayout(viewprojectpanel);
        viewprojectpanel.setLayout(viewprojectpanelLayout);
        viewprojectpanelLayout.setHorizontalGroup(
            viewprojectpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
        );
        viewprojectpanelLayout.setVerticalGroup(
            viewprojectpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
        );

        cardpanels.add(viewprojectpanel, "card4");

        updatebugspanel.setBackground(new java.awt.Color(255, 255, 255));

        UpdateBug.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "bug ID", "Bug Name", "project", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        UpdateBug.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateBugMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(UpdateBug);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Bug ID : ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Bug Name :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Project :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText(" Status :");

        updatebug.setBackground(new java.awt.Color(255, 255, 255));
        updatebug.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updatebug.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/Registry Editor_48px.png"))); // NOI18N
        updatebug.setText("Update");
        updatebug.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        updatebug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebugActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout updatebugspanelLayout = new javax.swing.GroupLayout(updatebugspanel);
        updatebugspanel.setLayout(updatebugspanelLayout);
        updatebugspanelLayout.setHorizontalGroup(
            updatebugspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updatebugspanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updatebugspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addGroup(updatebugspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updatebugspanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(updatebugspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BugIDTEXT, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(BugNameTEXT)
                            .addComponent(projectTEXT)
                            .addComponent(statusTEXT))
                        .addGap(218, 218, 218))
                    .addGroup(updatebugspanelLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(updatebug, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        updatebugspanelLayout.setVerticalGroup(
            updatebugspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
            .addGroup(updatebugspanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updatebugspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(BugIDTEXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(updatebugspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(BugNameTEXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(updatebugspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(projectTEXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(updatebugspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(statusTEXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(updatebug, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardpanels.add(updatebugspanel, "card3");

        resetmydatapanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("UserName : ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Password : ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Email :");

        updateData.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/Registry Editor_48px.png"))); // NOI18N
        updateData.setText("Update ^_^");
        updateData.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        updateData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout resetmydatapanelLayout = new javax.swing.GroupLayout(resetmydatapanel);
        resetmydatapanel.setLayout(resetmydatapanelLayout);
        resetmydatapanelLayout.setHorizontalGroup(
            resetmydatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resetmydatapanelLayout.createSequentialGroup()
                .addGroup(resetmydatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(resetmydatapanelLayout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addGroup(resetmydatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(133, 133, 133)
                        .addGroup(resetmydatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Password, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(UserName)
                            .addComponent(EamilReset)))
                    .addGroup(resetmydatapanelLayout.createSequentialGroup()
                        .addGap(393, 393, 393)
                        .addComponent(updateData)))
                .addContainerGap(355, Short.MAX_VALUE))
        );
        resetmydatapanelLayout.setVerticalGroup(
            resetmydatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resetmydatapanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(resetmydatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(38, 38, 38)
                .addGroup(resetmydatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(resetmydatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EamilReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(63, 63, 63)
                .addComponent(updateData, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        cardpanels.add(resetmydatapanel, "card2");

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/Administrator Male_48px.png"))); // NOI18N
        jLabel2.setText(" Developer -_-");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Back.setBackground(new java.awt.Color(255, 255, 255));
        Back.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/back.png"))); // NOI18N
        Back.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/es.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardpanels, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1))
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardpanels, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1212, 588));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        menu m =new menu();
        m.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void viewbugsptnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbugsptnActionPerformed
         loadprojectandbug();
        cardpanels.removeAll();
        cardpanels.add(viewbugspanel);
        cardpanels.repaint();
        cardpanels.revalidate();
    }//GEN-LAST:event_viewbugsptnActionPerformed

    private void updatebugsptnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebugsptnActionPerformed
       loadBug();
        cardpanels.removeAll();
        cardpanels.add(updatebugspanel);
        cardpanels.repaint();
        cardpanels.revalidate();
    }//GEN-LAST:event_updatebugsptnActionPerformed

    private void resetmydataptnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetmydataptnActionPerformed

        UserName.setText(DevloperName);
        Password.setText(DeveloperPassword);
        EamilReset.setText(DeveloperEmail);
        

        cardpanels.removeAll();
        cardpanels.add(resetmydatapanel);
        cardpanels.repaint();
        cardpanels.revalidate();
    }//GEN-LAST:event_resetmydataptnActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        menu show = new menu();
        show.setVisible(true);
        this.hide();

    }//GEN-LAST:event_BackActionPerformed

    private void UpdateBugMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateBugMouseClicked
            int row = UpdateBug.getSelectedRow();
            status = UpdateBug.getModel().getValueAt(row, 3).toString(); 
            Bug_ID = UpdateBug.getModel().getValueAt(row, 0).toString();
            String Bug_Name = UpdateBug.getModel().getValueAt(row, 1).toString();
            String project = UpdateBug.getModel().getValueAt(row, 2).toString();
            String Bug_id = UpdateBug.getModel().getValueAt(row, 0).toString();
            String Status = UpdateBug.getModel().getValueAt(row, 3).toString();
            BugIDTEXT.setText(Bug_id);
            projectTEXT.setText(project);
            BugNameTEXT.setText(Bug_Name);
            statusTEXT.setText(Status);
    }//GEN-LAST:event_UpdateBugMouseClicked

    private void updatebugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebugActionPerformed
     
        if(ND.UpdateBug(Bug_ID , status))
        {
            JOptionPane.showMessageDialog(this, "Updated Successfully", "Done", JOptionPane.PLAIN_MESSAGE);
        }
        else  
        {
              JOptionPane.showMessageDialog(this, "Update Falied", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
        /*try {
            Connection C = DriverManager.getConnection(URL, USER, PASSWORD);
             String Q = "update bug set status = '"+status+"' where BugID = '"+Bug_ID+"';";
            Statement St = C.createStatement();
            St.executeUpdate(Q);
            
            System.out.println(Bug_ID +" " + status);
        } catch (SQLException e) {
          System.out.println("not updated");
        }*/
    }//GEN-LAST:event_updatebugActionPerformed

    private void updateDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDataActionPerformed
       String username = UserName.getText();
       String Password = this.Password.getText();
       String Email = EamilReset.getText();
      
       if(ND.ResetData(username , Password , Email , DeveloperId))
       {
            JOptionPane.showMessageDialog(this, "Update Successfully", "Done", JOptionPane.PLAIN_MESSAGE);
            this.hide();
            menu update = new menu();
            update.setVisible(true);
       }
       else 
       {
            JOptionPane.showMessageDialog(this, "Update Failed", "ERROR", JOptionPane.ERROR_MESSAGE);
       }
       /* try {
            Connection conn = DriverManager.getConnection(URL, USER, PASSWORD);
            String Query = "Update user set username = '"+username+"' , password = '"+Password+"' ,Email = '"+Email+"' WHERE ID = '"+DeveloperId+"'";
            Statement St = conn.createStatement();
            St.executeUpdate(Query);
            JOptionPane.showMessageDialog(this, "Updated Sucessfully", "Done", JOptionPane.PLAIN_MESSAGE);
        } catch (Exception e) {
               JOptionPane.showMessageDialog(this, "Update Failed", "ERROR", JOptionPane.ERROR_MESSAGE);
        }*/
     
    }//GEN-LAST:event_updateDataActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeveloperForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeveloperForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeveloperForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeveloperForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             //   new DeveloperForm(Dev).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTextField BugIDTEXT;
    private javax.swing.JTextField BugNameTEXT;
    private javax.swing.JTable Bugs;
    private javax.swing.JTextField EamilReset;
    private javax.swing.JTextField Password;
    private javax.swing.JTable UpdateBug;
    private javax.swing.JTextField UserName;
    private javax.swing.JPanel cardpanels;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField projectTEXT;
    private javax.swing.JPanel resetmydatapanel;
    private javax.swing.JButton resetmydataptn;
    private javax.swing.JTextField statusTEXT;
    private javax.swing.JButton updateData;
    private javax.swing.JButton updatebug;
    private javax.swing.JPanel updatebugspanel;
    private javax.swing.JButton updatebugsptn;
    private javax.swing.JPanel viewbugspanel;
    private javax.swing.JButton viewbugsptn;
    private javax.swing.JPanel viewprojectpanel;
    // End of variables declaration//GEN-END:variables
void loadprojectandbug()
    {
         Connection Conn = null ;
     
        try {
            
           Conn = (Connection) DriverManager.getConnection(URL, USER,PASSWORD);
            Statement ST = Conn.createStatement();
            ResultSet RS = ST.executeQuery("SELECT BugID , name , project from bug");
            while(Bugs.getRowCount() > 0)
            {
               ((DefaultTableModel)Bugs.getModel()).removeRow(0);
            }
            int col = RS.getMetaData().getColumnCount();
            while(RS.next())
            {
                Object [] rows = new Object[col];
                for(int i = 1 ; i<=col ; i++)
                {
                    rows[i-1] = RS.getObject(i);
                }
                ((DefaultTableModel)Bugs.getModel()).insertRow(RS.getRow() - 1, rows);
            }
            System.out.println("loaded projects");
            RS.close();
            ST.close();
        } catch (SQLException e) {
            System.out.println("NOt loaded projects");
        }
    }
void loadBug()
{
     Connection Conn = null ;
     
        try {
            
           Conn = (Connection) DriverManager.getConnection(URL, USER,PASSWORD);
            Statement ST = Conn.createStatement();
            ResultSet RS = ST.executeQuery("SELECT BugID , name , project , status from bug");
            while(UpdateBug.getRowCount() > 0)
            {
               ((DefaultTableModel)UpdateBug.getModel()).removeRow(0);
            }
            int col = RS.getMetaData().getColumnCount();
            while(RS.next())
            {
                Object [] rows = new Object[col];
                for(int i = 1 ; i<=col ; i++)
                {
                    rows[i-1] = RS.getObject(i);
                }
                ((DefaultTableModel)UpdateBug.getModel()).insertRow(RS.getRow() - 1, rows);
            }
            System.out.println("loaded projects");
            RS.close();
            ST.close();
        } catch (SQLException e) {
            System.out.println("NOt loaded projects");
        }
}

}


