/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static project1.Project1.PASSWORD;
import static project1.Project1.URL;
import static project1.Project1.USER;

/**
 *
 * @author flash 20-9-2018
 */
public class TesterForm extends javax.swing.JFrame {

    /**
     * Creates new form TesterForm
     */
    String status , 

    /**
     * Creates new form TesterForm
     */
    Bug_ID ;
    Tester newTester = null;
    String testerName , testerPassword,testerEmail,testerId,testerProject;
    public TesterForm(Tester tester) {
        initComponents();
        loadprojectandbug();
        String [] status = {"Done" , "Not Done"};
        JComboBox c = new JComboBox(status);
        UpdateBug.getColumnModel().getColumn(3).setCellEditor(new DefaultCellEditor(c));
        newTester = tester ;
        testerName = tester.getUsername();
        testerPassword = tester.getPassword();
         testerEmail = tester.getEmail();
         testerId = tester.getId();
         testerProject= tester.getProject();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        viewbugbtn = new javax.swing.JButton();
        createbugbtn = new javax.swing.JButton();
        updatebugsbtn = new javax.swing.JButton();
        bassingtobtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        cardpanels = new javax.swing.JPanel();
        createbugspanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Bug_id = new javax.swing.JTextField();
        bug_Name = new javax.swing.JTextField();
        createBUG = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        ViewBug = new javax.swing.JTable();
        updatebugspanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        statusTEXT = new javax.swing.JTextField();
        projectTEXT = new javax.swing.JTextField();
        BugNameTEXT = new javax.swing.JTextField();
        BugIDTEXT = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        UpdateBug = new javax.swing.JTable();
        updatebug = new javax.swing.JButton();
        bassingtopanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        updater = new javax.swing.JButton();
        viewprojectpanel = new javax.swing.JPanel();
        viewbugspanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(170, 548));

        viewbugbtn.setBackground(new java.awt.Color(0, 0, 51));
        viewbugbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewbugbtn.setForeground(new java.awt.Color(255, 255, 255));
        viewbugbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/View Details_48px.png"))); // NOI18N
        viewbugbtn.setText("view Bugs ");
        viewbugbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        viewbugbtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        viewbugbtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        viewbugbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbugbtnActionPerformed(evt);
            }
        });

        createbugbtn.setBackground(new java.awt.Color(0, 0, 51));
        createbugbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        createbugbtn.setForeground(new java.awt.Color(255, 255, 255));
        createbugbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/Create_48px.png"))); // NOI18N
        createbugbtn.setText("Create Bugs");
        createbugbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        createbugbtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        createbugbtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        createbugbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createbugbtnActionPerformed(evt);
            }
        });

        updatebugsbtn.setBackground(new java.awt.Color(0, 0, 51));
        updatebugsbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updatebugsbtn.setForeground(new java.awt.Color(255, 255, 255));
        updatebugsbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/Registry Editor_48px.png"))); // NOI18N
        updatebugsbtn.setText("Update Bugs");
        updatebugsbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        updatebugsbtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        updatebugsbtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        updatebugsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebugsbtnActionPerformed(evt);
            }
        });

        bassingtobtn.setBackground(new java.awt.Color(0, 0, 51));
        bassingtobtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bassingtobtn.setForeground(new java.awt.Color(255, 255, 255));
        bassingtobtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/Outgoing Data_32px.png"))); // NOI18N
        bassingtobtn.setText("Bassing To");
        bassingtobtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        bassingtobtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bassingtobtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bassingtobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bassingtobtnActionPerformed(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/Services_501px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewbugbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(createbugbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(updatebugsbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
            .addComponent(bassingtobtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(22, 22, 22)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addComponent(viewbugbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(createbugbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updatebugsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bassingtobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setText("We Are The Five Team ^_^");

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cardpanels.setBackground(new java.awt.Color(255, 255, 255));
        cardpanels.setLayout(new java.awt.CardLayout());

        createbugspanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Bug Name :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("bug ID :");

        createBUG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        createBUG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/Create_48px.png"))); // NOI18N
        createBUG.setText("Create Bug");
        createBUG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBUGActionPerformed(evt);
            }
        });

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        ViewBug.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bug ID", "Bug Name", "Project"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ViewBug.setGridColor(new java.awt.Color(0, 0, 102));
        ViewBug.setSelectionForeground(new java.awt.Color(102, 0, 102));
        jScrollPane1.setViewportView(ViewBug);

        javax.swing.GroupLayout createbugspanelLayout = new javax.swing.GroupLayout(createbugspanel);
        createbugspanel.setLayout(createbugspanelLayout);
        createbugspanelLayout.setHorizontalGroup(
            createbugspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createbugspanelLayout.createSequentialGroup()
                .addGroup(createbugspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createbugspanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(createbugspanelLayout.createSequentialGroup()
                        .addGroup(createbugspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(createbugspanelLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(createbugspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))
                                .addGap(24, 24, 24)
                                .addGroup(createbugspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bug_Name, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                    .addComponent(Bug_id)))
                            .addGroup(createbugspanelLayout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(createBUG)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        createbugspanelLayout.setVerticalGroup(
            createbugspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createbugspanelLayout.createSequentialGroup()
                .addGroup(createbugspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createbugspanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(createbugspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(bug_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(createbugspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(Bug_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addComponent(createBUG, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(createbugspanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardpanels.add(createbugspanel, "card4");

        updatebugspanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Bug ID");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Bug Name");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Project");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Status");

        UpdateBug.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "bug ID", "Bug Name", "project", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        UpdateBug.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateBugMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(UpdateBug);

        updatebug.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/Update User_64px.png"))); // NOI18N
        updatebug.setText("Update");
        updatebug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebugActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout updatebugspanelLayout = new javax.swing.GroupLayout(updatebugspanel);
        updatebugspanel.setLayout(updatebugspanelLayout);
        updatebugspanelLayout.setHorizontalGroup(
            updatebugspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updatebugspanelLayout.createSequentialGroup()
                .addGroup(updatebugspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updatebugspanelLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(updatebug))
                    .addGroup(updatebugspanelLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(updatebugspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(updatebugspanelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(63, 63, 63)
                                .addComponent(BugIDTEXT, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(updatebugspanelLayout.createSequentialGroup()
                                .addGroup(updatebugspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(42, 42, 42)
                                .addGroup(updatebugspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(projectTEXT, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BugNameTEXT, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(statusTEXT, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        updatebugspanelLayout.setVerticalGroup(
            updatebugspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
            .addGroup(updatebugspanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updatebugspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(BugIDTEXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(updatebugspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(BugNameTEXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(updatebugspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(projectTEXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(updatebugspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(statusTEXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updatebug, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        cardpanels.add(updatebugspanel, "card3");

        bassingtopanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Bug Name :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Assign to  ->");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        updater.setBackground(new java.awt.Color(255, 255, 255));
        updater.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updater.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/Update User_64px.png"))); // NOI18N
        updater.setText(" Update ");
        updater.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        updater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updaterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bassingtopanelLayout = new javax.swing.GroupLayout(bassingtopanel);
        bassingtopanel.setLayout(bassingtopanelLayout);
        bassingtopanelLayout.setHorizontalGroup(
            bassingtopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bassingtopanelLayout.createSequentialGroup()
                .addGroup(bassingtopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bassingtopanelLayout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addGroup(bassingtopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11))
                        .addGap(63, 63, 63)
                        .addGroup(bassingtopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox2, 0, 179, Short.MAX_VALUE)
                            .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(bassingtopanelLayout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addComponent(updater, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(359, Short.MAX_VALUE))
        );
        bassingtopanelLayout.setVerticalGroup(
            bassingtopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bassingtopanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(bassingtopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(bassingtopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(updater)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        cardpanels.add(bassingtopanel, "card2");

        viewprojectpanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout viewprojectpanelLayout = new javax.swing.GroupLayout(viewprojectpanel);
        viewprojectpanel.setLayout(viewprojectpanelLayout);
        viewprojectpanelLayout.setHorizontalGroup(
            viewprojectpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 935, Short.MAX_VALUE)
        );
        viewprojectpanelLayout.setVerticalGroup(
            viewprojectpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        cardpanels.add(viewprojectpanel, "card6");

        viewbugspanel.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout viewbugspanelLayout = new javax.swing.GroupLayout(viewbugspanel);
        viewbugspanel.setLayout(viewbugspanelLayout);
        viewbugspanelLayout.setHorizontalGroup(
            viewbugspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 935, Short.MAX_VALUE)
        );
        viewbugspanelLayout.setVerticalGroup(
            viewbugspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        cardpanels.add(viewbugspanel, "card5");

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/tester_48px.png"))); // NOI18N
        jLabel3.setText("Tester-_-");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 51)));
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/es.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/back.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(4, 4, 4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(604, 604, 604)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(cardpanels, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1626, 1626, 1626))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(cardpanels, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1178, 571));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       // TODO add your handling code here:
        menu m =new menu();
        m.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void viewbugbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbugbtnActionPerformed
      //loadprojectandbug();
        cardpanels.removeAll();
        cardpanels.add(viewbugspanel);
        cardpanels.repaint();
        cardpanels.revalidate();
    }//GEN-LAST:event_viewbugbtnActionPerformed

    private void createbugbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createbugbtnActionPerformed
       fillcombo();
        cardpanels.removeAll();
        cardpanels.add(createbugspanel);
        cardpanels.repaint();
        cardpanels.revalidate();
    }//GEN-LAST:event_createbugbtnActionPerformed

    private void updatebugsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebugsbtnActionPerformed
       loadBug();
        cardpanels.removeAll();
        cardpanels.add(updatebugspanel);
        cardpanels.repaint();
        cardpanels.revalidate();
    }//GEN-LAST:event_updatebugsbtnActionPerformed

    private void bassingtobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bassingtobtnActionPerformed
        loadBugName();
        loaddevelopername();
        cardpanels.removeAll();
        cardpanels.add(bassingtopanel);
        cardpanels.repaint();
        cardpanels.revalidate();
    }//GEN-LAST:event_bassingtobtnActionPerformed

    private void createBUGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBUGActionPerformed
       String BugName = bug_Name.getText();
       String BugID = Bug_id.getText();
       if(newTester.CreateBug(BugName, BugID, jComboBox1.getSelectedItem().toString()))
       {
           JOptionPane.showMessageDialog(this, "Updated Successfully", "Done", JOptionPane.PLAIN_MESSAGE);
       }
       else
       {
              JOptionPane.showMessageDialog(this, "Update Falied", "ERROR", JOptionPane.ERROR_MESSAGE);
       }
        /*try {
            Connection Conn = DriverManager.getConnection(URL, USER, PASSWORD);
            String Query = "INSERT INTO `database`.bug (BugID, name, project, Status)" +
	"VALUES ('"+BugID+"', '"+BugName+"', '"+jComboBox1.getSelectedItem().toString()+"', 'Not Done');";
            Statement St = Conn.createStatement();
            St.executeUpdate(Query);
            System.out.println("Done");
        } catch (SQLException e) {
             System.out.println("Again");
        }*/
    }//GEN-LAST:event_createBUGActionPerformed

    private void UpdateBugMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateBugMouseClicked
        int row = UpdateBug.getSelectedRow();
        status = UpdateBug.getModel().getValueAt(row, 3).toString();
        Bug_ID = UpdateBug.getModel().getValueAt(row, 0).toString();
        String Bug_Name = UpdateBug.getModel().getValueAt(row, 1).toString();
        String project = UpdateBug.getModel().getValueAt(row, 2).toString();
        String Bug_id = UpdateBug.getModel().getValueAt(row, 0).toString();
        String Status = UpdateBug.getModel().getValueAt(row, 3).toString();
        BugIDTEXT.setText(Bug_id);
        projectTEXT.setText(project);
        BugNameTEXT.setText(Bug_Name);
        statusTEXT.setText(Status);
    }//GEN-LAST:event_UpdateBugMouseClicked

    private void updatebugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebugActionPerformed
    if(newTester.UpdateBug(status, Bug_ID))
    {
         JOptionPane.showMessageDialog(this, "Updated Successfully", "Done", JOptionPane.PLAIN_MESSAGE);
    }
    else
    {
         JOptionPane.showMessageDialog(this, "Update Falied", "ERROR", JOptionPane.ERROR_MESSAGE);
    }
        /*try {
            Connection C = DriverManager.getConnection(URL, USER, PASSWORD);
            String Q = "update bug set status = '"+status+"' where BugID = '"+Bug_ID+"';";
            Statement St = C.createStatement();
            St.executeUpdate(Q);

            System.out.println(Bug_ID +" " + status);
        } catch (SQLException e) {
            System.out.println("not updated");
        }*/
    }//GEN-LAST:event_updatebugActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void updaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updaterActionPerformed
       String DEVName = jComboBox3.getSelectedItem().toString();
       String BUGName = jComboBox2.getSelectedItem().toString();
       if(newTester.AssignBug(DEVName, BUGName))
       {
           JOptionPane.showMessageDialog(this, "Successfully Updated", "Done", JOptionPane.PLAIN_MESSAGE);
       }
       else
       {
           JOptionPane.showMessageDialog(this, "Update Failed", "ERROR", JOptionPane.ERROR_MESSAGE);
       }
        /*try {
            String Query ="UPDATE bug set devname = '"+DEVName+"' WHERE name = '"+BUGName+"'";
            Connection Conn = DriverManager.getConnection(URL, USER, PASSWORD);
            Statement St = Conn.createStatement();
            St.executeUpdate(Query);
            JOptionPane.showMessageDialog(this, "Successfully Updated", "Done", JOptionPane.PLAIN_MESSAGE);
        } catch (SQLException e) {
           JOptionPane.showMessageDialog(this, "Update Failed", "ERROR", JOptionPane.ERROR_MESSAGE);
        }*/
    }//GEN-LAST:event_updaterActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        menu show = new menu();
        show.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TesterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TesterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TesterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TesterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new TesterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BugIDTEXT;
    private javax.swing.JTextField BugNameTEXT;
    private javax.swing.JTextField Bug_id;
    private javax.swing.JTable UpdateBug;
    private javax.swing.JTable ViewBug;
    private javax.swing.JButton bassingtobtn;
    private javax.swing.JPanel bassingtopanel;
    private javax.swing.JTextField bug_Name;
    private javax.swing.JPanel cardpanels;
    private javax.swing.JButton createBUG;
    private javax.swing.JButton createbugbtn;
    private javax.swing.JPanel createbugspanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField projectTEXT;
    private javax.swing.JTextField statusTEXT;
    private javax.swing.JButton updatebug;
    private javax.swing.JButton updatebugsbtn;
    private javax.swing.JPanel updatebugspanel;
    private javax.swing.JButton updater;
    private javax.swing.JButton viewbugbtn;
    private javax.swing.JPanel viewbugspanel;
    private javax.swing.JPanel viewprojectpanel;
    // End of variables declaration//GEN-END:variables
void loadprojectandbug()
    {
         Connection Conn = null ;
     
        try {
            
           Conn = (Connection) DriverManager.getConnection(URL, USER,PASSWORD);
            Statement ST = Conn.createStatement();
            ResultSet RS = ST.executeQuery("SELECT BugID , name , project from bug");
            while(ViewBug.getRowCount() > 0)
            {
               ((DefaultTableModel)ViewBug.getModel()).removeRow(0);
            }
            int col = RS.getMetaData().getColumnCount();
            while(RS.next())
            {
                Object [] rows = new Object[col];
                for(int i = 1 ; i<=col ; i++)
                {
                    rows[i-1] = RS.getObject(i);
                }
                ((DefaultTableModel)ViewBug.getModel()).insertRow(RS.getRow() - 1, rows);
            }
            System.out.println("loaded bugs");
            RS.close();
            ST.close();
        } catch (SQLException e) {
            System.out.println("NOt loaded bugs");
        }
    }
public void fillcombo()
{
    try {
        String Query = "SELECT project from user" ;
        Connection Conn = DriverManager.getConnection(URL, USER, PASSWORD);
        Statement St = Conn.createStatement();
        ResultSet Rs = St.executeQuery(Query);
        while(Rs.next())
        {
            jComboBox1.addItem(Rs.getString(1));
        }
        System.out.println("filled");
    } catch (SQLException e) {
        System.out.println("not filled , try again");
    }
}
void loadBug()
{
     Connection Conn = null ;
     
        try {
            
           Conn = (Connection) DriverManager.getConnection(URL, USER,PASSWORD);
            Statement ST = Conn.createStatement();
            ResultSet RS = ST.executeQuery("SELECT BugID , name , project , status from bug");
            while(UpdateBug.getRowCount() > 0)
            {
               ((DefaultTableModel)UpdateBug.getModel()).removeRow(0);
            }
            int col = RS.getMetaData().getColumnCount();
            while(RS.next())
            {
                Object [] rows = new Object[col];
                for(int i = 1 ; i<=col ; i++)
                {
                    rows[i-1] = RS.getObject(i);
                }
                ((DefaultTableModel)UpdateBug.getModel()).insertRow(RS.getRow() - 1, rows);
            }
            System.out.println("loaded projects");
            RS.close();
            ST.close();
        } catch (SQLException e) {
            System.out.println("NOt loaded projects");
        }
}
void loadBugName()
{
    try {
        String Query = "SELECT name from bug" ;
        Connection Conn = DriverManager.getConnection(URL, USER, PASSWORD);
        Statement St = Conn.createStatement();
        ResultSet Rs = St.executeQuery(Query);
        while(Rs.next())
        {
            jComboBox2.addItem(Rs.getString(1));
        }
        System.out.println("filled");
    } catch (SQLException e) {
        System.out.println("not filled , try again");
    }
}
public void loaddevelopername()
{
     try {
        String Query = "SELECT username from user WHERE job = 'developer'" ;
        Connection Conn = DriverManager.getConnection(URL, USER, PASSWORD);
        Statement St = Conn.createStatement();
        ResultSet Rs = St.executeQuery(Query);
        while(Rs.next())
        {
            jComboBox3.addItem(Rs.getString(1));
        }
        System.out.println("filled dev");
    } catch (SQLException e) {
        System.out.println("not filled , try again");
    }
}
}
